### ISSUE TITLE
Is it possible that the links for the github repositories and playground urls can actually be clickable?

### ISSUE THREAD

**Issue by chaoticbit** [amitmishrg/code-resume#3]

**Comment by amitmishrg** [comment]
It's not supported yet. But I'm thinking to add this feature I'll add this asap.

**Comment by chaoticbit** [comment]
wow!! Will be waiting for that since I just forked and want to deploy this to heroku

**Comment by amitmishrg** [comment]
Hey, Supported links as clickable.
You just need to add link to as normal HTML anchor tag like--
`<a href=''something">'something'</a> `

**Comment by chaoticbit** [comment]
I mean in the data...for example I have an npm link for my project. Since the data is a string which is returned and since it is then populated in <pre> the html is escaped. I want to know if the links in Projects and Playgrounds are clickable...if yes can you provide an example on how I can achieve that

**Comment by amitmishrg** [comment]
I'm just checking in data if any string contains HTML tag then rendering string as html.
So you need to add link this -
 ```
Projects = () =>  {
     zeta: {
       url: <a target='_blank' href='npm-link'>npm-link</a>
      }
 }
```

**Comment by chaoticbit** [comment]
Oh you committed it just now that what's. I did not had that change. Works perfectly
