### ISSUE TITLE
when i clicked export as pdf button pressent 404

### ISSUE THREAD

**Issue by kirkzhangtech** [amitmishrg/code-resume#5]
![image](https://user-images.githubusercontent.com/46363359/78106679-704e9980-7426-11ea-9a16-53d4f3d14dd1.png)

**Comment by amitmishrg** [comment]
Run your project through `yarn start` or `npm run start`.
It will serve through node js.

**Comment by kirkzhangtech** [comment]
i wanne liked this resmue not page source resmue&nbsp;&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Amit Mishra"<notifications@github.com&gt;; 
发送时间: 2020年4月1日(星期三) 下午2:47
收件人: "amitmishrg/code-resume"<code-resume@noreply.github.com&gt;; 
抄送: "张士明"<zxc741208584@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [amitmishrg/code-resume] when i clicked export as pdf button pressent 404 (#5)





 
Run your project through yarn start or npm run start.
 It will serve through node js.

**Comment by amitmishrg** [comment]
??

**Comment by kirkzhangtech** [comment]
**how to create this resume throught your project **




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Amit Mishra"<notifications@github.com&gt;; 
发送时间: 2020年4月1日(星期三) 下午3:42
收件人: "amitmishrg/code-resume"<code-resume@noreply.github.com&gt;; 
抄送: "张士明"<zxc741208584@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [amitmishrg/code-resume] when i clicked export as pdf button pressent 404 (#5)





 
??

**Comment by amitmishrg** [comment]
If you just want to export resume then run your project with `yarn start` or  `npm run start.`  
Then click on export as pdf it will automatically download your resume.
If you want to update the content then please follow the doc https://github.com/amitmishrg/code-resume#quick-start
